language: ruby
rvm:
  - 2.1.5

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
    - master
    - /pages-(.*)/

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production

sudo: false
