title: Партий Дизайнеров Кыргызстана
email: amywoodehy@gmail.com
description: > 
  Чтобы обсмеять политическую обстановку в Кыргызстане группа дизайнеров создала свою интернет партию.
  Движение получило название Партия Дизайнеров Кыргызстана и началась с пользователя Никиты Тарасенко.
baseurl: "" 
url: "https://jpegjolu.ga" 
twitter_username: socialamywoo
github_username:  amywoodehy

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
disqus:
  shortname: jpegjolu-ga
google_analitycs: UA-48245585-4
